export interface OnboardingInfo {
    id:number;
    issigned:boolean;
    signedon:string;
    signedby:string;
    firstname: string;
    lastname: string;
    middlename: string;
    designation: string;
    employeeid: string;
    dob: string;
    superannuation: string;
    payscaleCode: number;
    payscaleName: string;
    email: string;
    phoneno1: string;
    phoneno2: string;
    ministry: string;
    department: string;
    organization: string;
    organizationOfficeId: number;
    organizationOfficeName: string;
    oaddress: string;
    city: string;
    state: string;
    district: string;
    pincode2: string;
    file: string;
    englishname: string;
    approvingdesignation: string;
    approvingemployeeid: string;
    approvingemail: string;
    phoneno3: string;
    phoneno4: string;
    approvingfile: string;
    nodalofficer: string;
    approving: string;
    checkbox1: string;
    checkbox2: string;
    checkbox3: string;
    strength: string;
    file1: string;
    file2: string;
    // rmFlag:string;
    cghsCities: [];
}
